'use server'

import { createClient } from '@/utils/supabase/server';
import { getSessionUid } from './auth-session';
import { BreedingSeries, BreedingTask } from '@/types/supabase';
import { revalidatePath } from 'next/cache';

/**
 * Helper: Get Queen Year Color
 */
function getQueenYearColor(year: number): 'WHITE' | 'YELLOW' | 'RED' | 'GREEN' | 'BLUE' {
  const colors: Array<'WHITE' | 'YELLOW' | 'RED' | 'GREEN' | 'BLUE'> = ['BLUE', 'WHITE', 'YELLOW', 'RED', 'GREEN'];
  return colors[year % 5];
}

/**
 * Get all breeding series for current breeder
 */
export async function getBreedingSeries(): Promise<{ data: BreedingSeries[]; error: string | null }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { data: [], error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    const { data, error } = await supabase
      .from('breeding_series')
      .select('*')
      .eq('breeder_id', uid)
      .order('start_date', { ascending: false });

    if (error) {
      console.error('Error fetching breeding series:', error);
      return { data: [], error: error.message };
    }

    // Calculate efficiency
    const processedData: BreedingSeries[] = (data || []).map((item: any) => {
      const acceptanceEfficiency = item.larvae_count > 0 
        ? (item.accepted_count / item.larvae_count) * 100 
        : 0;
      const hatchingEfficiency = item.accepted_count > 0 
        ? (item.hatched_count / item.accepted_count) * 100 
        : 0;

      return {
        ...item,
        acceptance_efficiency: Math.round(acceptanceEfficiency * 10) / 10,
        hatching_efficiency: Math.round(hatchingEfficiency * 10) / 10,
      };
    });

    return { data: processedData, error: null };
  } catch (err) {
    console.error('Error in getBreedingSeries:', err);
    return { data: [], error: 'Wystąpił błąd podczas pobierania serii' };
  }
}

/**
 * Get single breeding series with tasks
 */
export async function getBreedingSeriesById(seriesId: string): Promise<{ data: BreedingSeries | null; error: string | null }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { data: null, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    const { data, error } = await supabase
      .from('breeding_series')
      .select('*')
      .eq('id', seriesId)
      .eq('breeder_id', uid)
      .single();

    if (error || !data) {
      return { data: null, error: error?.message || 'Seria nie znaleziona' };
    }

    // Calculate efficiency
    const acceptanceEfficiency = data.larvae_count > 0 
      ? (data.accepted_count / data.larvae_count) * 100 
      : 0;
    const hatchingEfficiency = data.accepted_count > 0 
      ? (data.hatched_count / data.accepted_count) * 100 
      : 0;

    return {
      data: {
        ...data,
        acceptance_efficiency: Math.round(acceptanceEfficiency * 10) / 10,
        hatching_efficiency: Math.round(hatchingEfficiency * 10) / 10,
      },
      error: null
    };
  } catch (err) {
    console.error('Error in getBreedingSeriesById:', err);
    return { data: null, error: 'Wystąpił błąd podczas pobierania serii' };
  }
}

/**
 * Create new breeding series
 * Automatically generates tasks via database trigger
 */
export async function createBreedingSeries(data: {
  series_number: string;
  lineage?: string;
  start_date: string;
  larvae_count: number;
  mother_queen_id?: string;
  notes?: string;
}): Promise<{ success: boolean; data?: BreedingSeries; error?: string }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { success: false, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    const { data: series, error } = await supabase
      .from('breeding_series')
      .insert({
        breeder_id: uid,
        series_number: data.series_number,
        lineage: data.lineage,
        start_date: data.start_date,
        larvae_count: data.larvae_count,
        mother_queen_id: data.mother_queen_id,
        notes: data.notes,
        status: 'IN_PROGRESS',
        accepted_count: 0,
        hatched_count: 0,
      })
      .select()
      .single();

    if (error) {
      console.error('Error creating breeding series:', error);
      return { success: false, error: error.message };
    }

    // Tasks are auto-generated by database trigger
    revalidatePath('/dashboard/breeder/production');
    return { success: true, data: series };
  } catch (err) {
    console.error('Error in createBreedingSeries:', err);
    return { success: false, error: 'Wystąpił błąd podczas tworzenia serii' };
  }
}

/**
 * Update breeding series
 */
export async function updateBreedingSeries(
  seriesId: string,
  updates: Partial<{
    series_number: string;
    lineage: string;
    start_date: string;
    larvae_count: number;
    accepted_count: number;
    hatched_count: number;
    mother_queen_id: string;
    notes: string;
    status: 'PLANNED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
  }>
): Promise<{ success: boolean; error?: string }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { success: false, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    // Verify ownership
    const { data: existing } = await supabase
      .from('breeding_series')
      .select('id')
      .eq('id', seriesId)
      .eq('breeder_id', uid)
      .single();

    if (!existing) {
      return { success: false, error: 'Seria nie znaleziona lub brak uprawnień' };
    }

    const { error } = await supabase
      .from('breeding_series')
      .update(updates)
      .eq('id', seriesId)
      .eq('breeder_id', uid);

    if (error) {
      console.error('Error updating breeding series:', error);
      return { success: false, error: error.message };
    }

    revalidatePath('/dashboard/breeder/production');
    return { success: true };
  } catch (err) {
    console.error('Error in updateBreedingSeries:', err);
    return { success: false, error: 'Wystąpił błąd podczas aktualizacji serii' };
  }
}

/**
 * Get tasks for a breeding series
 */
export async function getBreedingTasks(seriesId?: string): Promise<{ data: BreedingTask[]; error: string | null }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { data: [], error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    let query = supabase
      .from('breeding_tasks')
      .select('*')
      .eq('breeder_id', uid)
      .order('scheduled_date', { ascending: true });

    if (seriesId) {
      query = query.eq('series_id', seriesId);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Error fetching breeding tasks:', error);
      return { data: [], error: error.message };
    }

    return { data: data || [], error: null };
  } catch (err) {
    console.error('Error in getBreedingTasks:', err);
    return { data: [], error: 'Wystąpił błąd podczas pobierania zadań' };
  }
}

/**
 * Update task status
 */
export async function updateBreedingTask(
  taskId: string,
  status: 'PENDING' | 'COMPLETED' | 'SKIPPED',
  notes?: string
): Promise<{ success: boolean; error?: string }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { success: false, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    const updateData: any = {
      status,
      notes,
    };

    if (status === 'COMPLETED') {
      updateData.completed_at = new Date().toISOString();
    }

    const { error } = await supabase
      .from('breeding_tasks')
      .update(updateData)
      .eq('id', taskId)
      .eq('breeder_id', uid);

    if (error) {
      console.error('Error updating task:', error);
      return { success: false, error: error.message };
    }

    revalidatePath('/dashboard/breeder/production');
    return { success: true };
  } catch (err) {
    console.error('Error in updateBreedingTask:', err);
    return { success: false, error: 'Wystąpił błąd podczas aktualizacji zadania' };
  }
}

/**
 * Delete breeding series
 */
export async function deleteBreedingSeries(seriesId: string): Promise<{ success: boolean; error?: string }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { success: false, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    // Verify ownership
    const { data: existing } = await supabase
      .from('breeding_series')
      .select('id')
      .eq('id', seriesId)
      .eq('breeder_id', uid)
      .single();

    if (!existing) {
      return { success: false, error: 'Seria nie znaleziona lub brak uprawnień' };
    }

    const { error } = await supabase
      .from('breeding_series')
      .delete()
      .eq('id', seriesId)
      .eq('breeder_id', uid);

    if (error) {
      console.error('Error deleting breeding series:', error);
      return { success: false, error: error.message };
    }

    revalidatePath('/dashboard/breeder/production');
    return { success: true };
  } catch (err) {
    console.error('Error in deleteBreedingSeries:', err);
    return { success: false, error: 'Wystąpił błąd podczas usuwania serii' };
  }
}


