'use server'

import { createClient } from '@/utils/supabase/server';
import { getSessionUid } from './auth-session';
import { BreedingSeries, BreedingTask } from '@/types/supabase';
import { revalidatePath } from 'next/cache';

/**
 * Get all breeding series for current user
 */
export async function getBreedingSeries(): Promise<{ data: BreedingSeries[]; error: string | null }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { data: [], error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    const { data, error } = await supabase
      .from('breeding_series')
      .select(`
        *,
        breeding_mother:breeding_mothers!mother_id (
          id,
          name,
          breed,
          line,
          year,
          insemination_method
        )
      `)
      .eq('user_id', uid)
      .order('start_date', { ascending: false });

    if (error) {
      console.error('Error fetching breeding series:', error);
      return { data: [], error: error.message };
    }

    // Calculate efficiency
    const processedData: BreedingSeries[] = (data || []).map((item: any) => {
      const breedingMother = Array.isArray(item.breeding_mother) ? item.breeding_mother[0] : item.breeding_mother;
      const acceptanceEfficiency = item.larvae_count > 0 
        ? (item.accepted_count / item.larvae_count) * 100 
        : 0;
      const hatchingEfficiency = item.accepted_count > 0 
        ? (item.hatched_count / item.accepted_count) * 100 
        : 0;

      return {
        ...item,
        breeding_mother: breedingMother || undefined,
        acceptance_efficiency: Math.round(acceptanceEfficiency * 10) / 10,
        hatching_efficiency: Math.round(hatchingEfficiency * 10) / 10,
      };
    });

    return { data: processedData, error: null };
  } catch (err) {
    console.error('Error in getBreedingSeries:', err);
    return { data: [], error: 'Wystąpił błąd podczas pobierania serii' };
  }
}

/**
 * Create new breeding series
 * Automatically generates tasks via database trigger
 */
export async function createBreedingSeries(data: {
  name: string;
  mother_id?: string;
  start_date: string;
  larvae_count: number;
}): Promise<{ success: boolean; data?: BreedingSeries; error?: string }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { success: false, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    if (!data.mother_id) {
      return { success: false, error: 'Matka reprodukcyjna jest wymagana' };
    }

    const { data: series, error } = await supabase
      .from('breeding_series')
      .insert({
        user_id: uid,
        name: data.name,
        mother_id: data.mother_id,
        start_date: data.start_date,
        larvae_count: data.larvae_count,
        accepted_count: 0,
        hatched_count: 0,
        status: 'ACTIVE',
      })
      .select()
      .single();

    if (error) {
      console.error('Error creating breeding series:', error);
      return { success: false, error: error.message };
    }

    // Tasks are auto-generated by database trigger
    revalidatePath('/dashboard/breeder/production');
    return { success: true, data: series };
  } catch (err) {
    console.error('Error in createBreedingSeries:', err);
    return { success: false, error: 'Wystąpił błąd podczas tworzenia serii' };
  }
}

/**
 * Update breeding series
 */
export async function updateBreedingSeries(
  seriesId: string,
  updates: Partial<{
    name: string;
    mother_id: string;
    start_date: string;
    larvae_count: number;
    accepted_count: number;
    hatched_count: number;
    status: 'ACTIVE' | 'COMPLETED' | 'CANCELLED';
  }>
): Promise<{ success: boolean; error?: string }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { success: false, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    // Verify ownership
    const { data: existing } = await supabase
      .from('breeding_series')
      .select('id')
      .eq('id', seriesId)
      .eq('user_id', uid)
      .single();

    if (!existing) {
      return { success: false, error: 'Seria nie znaleziona lub brak uprawnień' };
    }

    const { error } = await supabase
      .from('breeding_series')
      .update(updates)
      .eq('id', seriesId)
      .eq('user_id', uid);

    if (error) {
      console.error('Error updating breeding series:', error);
      return { success: false, error: error.message };
    }

    revalidatePath('/dashboard/breeder/production');
    return { success: true };
  } catch (err) {
    console.error('Error in updateBreedingSeries:', err);
    return { success: false, error: 'Wystąpił błąd podczas aktualizacji serii' };
  }
}

/**
 * Get tasks for breeding series
 */
export async function getBreedingTasks(seriesId?: string): Promise<{ data: BreedingTask[]; error: string | null }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { data: [], error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    let query = supabase
      .from('breeding_tasks')
      .select(`
        *,
        series:breeding_series (
          id,
          name,
          start_date
        )
      `)
      .eq('user_id', uid)
      .order('planned_date', { ascending: true });

    if (seriesId) {
      query = query.eq('series_id', seriesId);
    }

    const { data, error } = await query;

    if (error) {
      console.error('Error fetching breeding tasks:', error);
      return { data: [], error: error.message };
    }

    // Process series join
    const processedData: BreedingTask[] = (data || []).map((item: any) => {
      const seriesData = Array.isArray(item.series) ? item.series[0] : item.series;
      return {
        ...item,
        series: seriesData || undefined,
      };
    });

    return { data: processedData, error: null };
  } catch (err) {
    console.error('Error in getBreedingTasks:', err);
    return { data: [], error: 'Wystąpił błąd podczas pobierania zadań' };
  }
}

/**
 * Get overdue tasks (for import function)
 */
export async function getOverdueTasks(): Promise<{ success: boolean; data?: BreedingTask[]; error?: string }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { success: false, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    const today = new Date().toISOString().split('T')[0];
    
    const { data, error } = await supabase
      .from('breeding_tasks')
      .select(`
        *,
        series:breeding_series (
          id,
          name,
          start_date
        )
      `)
      .eq('user_id', uid)
      .is('completed_at', null)
      .lt('planned_date', today)
      .eq('status', 'PENDING')
      .order('planned_date', { ascending: true });

    if (error) {
      console.error('Error fetching overdue tasks:', error);
      return { success: false, error: error.message };
    }

    // Process series join
    const processedData: BreedingTask[] = (data || []).map((item: any) => {
      const seriesData = Array.isArray(item.series) ? item.series[0] : item.series;
      return {
        ...item,
        series: seriesData || undefined,
      };
    });

    return { success: true, data: processedData };
  } catch (err) {
    console.error('Error in getOverdueTasks:', err);
    return { success: false, error: 'Wystąpił błąd podczas pobierania przeterminowanych zadań' };
  }
}

/**
 * Complete task (set completed_at = NOW())
 */
export async function completeBreedingTask(
  taskId: string,
  notes?: string
): Promise<{ success: boolean; error?: string }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { success: false, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    const { error } = await supabase
      .from('breeding_tasks')
      .update({
        status: 'COMPLETED',
        completed_at: new Date().toISOString(),
        notes: notes,
      })
      .eq('id', taskId)
      .eq('user_id', uid);

    if (error) {
      console.error('Error completing task:', error);
      return { success: false, error: error.message };
    }

    revalidatePath('/dashboard/breeder/production');
    revalidatePath('/dashboard/breeder/calendar');
    return { success: true };
  } catch (err) {
    console.error('Error in completeBreedingTask:', err);
    return { success: false, error: 'Wystąpił błąd podczas oznaczania zadania' };
  }
}

/**
 * Skip task
 */
export async function skipBreedingTask(
  taskId: string,
  notes?: string
): Promise<{ success: boolean; error?: string }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { success: false, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    const { error } = await supabase
      .from('breeding_tasks')
      .update({
        status: 'SKIPPED',
        notes: notes,
      })
      .eq('id', taskId)
      .eq('user_id', uid);

    if (error) {
      console.error('Error skipping task:', error);
      return { success: false, error: error.message };
    }

    revalidatePath('/dashboard/breeder/production');
    revalidatePath('/dashboard/breeder/calendar');
    return { success: true };
  } catch (err) {
    console.error('Error in skipBreedingTask:', err);
    return { success: false, error: 'Wystąpił błąd podczas pomijania zadania' };
  }
}

/**
 * Delete breeding series
 */
export async function deleteBreedingSeries(seriesId: string): Promise<{ success: boolean; error?: string }> {
  const uid = await getSessionUid();
  if (!uid) {
    return { success: false, error: 'Unauthorized' };
  }

  const supabase = createClient();

  try {
    // Verify ownership
    const { data: existing } = await supabase
      .from('breeding_series')
      .select('id')
      .eq('id', seriesId)
      .eq('user_id', uid)
      .single();

    if (!existing) {
      return { success: false, error: 'Seria nie znaleziona lub brak uprawnień' };
    }

    const { error } = await supabase
      .from('breeding_series')
      .delete()
      .eq('id', seriesId)
      .eq('user_id', uid);

    if (error) {
      console.error('Error deleting breeding series:', error);
      return { success: false, error: error.message };
    }

    revalidatePath('/dashboard/breeder/production');
    return { success: true };
  } catch (err) {
    console.error('Error in deleteBreedingSeries:', err);
    return { success: false, error: 'Wystąpił błąd podczas usuwania serii' };
  }
}

